new3

diff --git a/.github/workflows/test_fleet_health.yml b/.github/workflows/test_fleet_health.yml
--- a/.github/workflows/test_fleet_health.yml
+++ b/.github/workflows/test_fleet_health.yml
@@ -3,7 +3,6 @@ name: Test Fleet health and Env Variables
 on:
   workflow_call:
 
-
 permissions:
   id-token: write
   contents: read
@@ -11,6 +10,7 @@ permissions:
 jobs:
   test:
     runs-on: ubuntu-latest
+
     steps:
       - uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -25,33 +25,38 @@ jobs:
             --document-name "AWS-RunShellScript" \
             --parameters '{"commands":[
               "hostname -I",
-              "docker --version 2>/dev/null  echo AWS CLI NOT INSTALLED",
-              "mysql --version 2>/dev/null || echo DOCKER NOT INSTALLED",
+              "docker --version 2>/dev/null || echo DOCKER NOT INSTALLED",
+              "aws --version 2>/dev/null || echo AWS CLI NOT INSTALLED",
+              "mysql --version 2>/dev/null || echo MYSQL NOT INSTALLED",
               "aws ssm get-parameters-by-path --path /application/banking --with-decryption --region us-east-1"
-              ]}' \
-            --query 'Command.CommandId' --output text \
+            ]}' \
+            --query "Command.CommandId" \
+            --output text \
             --region us-east-1)
-          echo "cmd_id"=$"CMD_ID" >> $GITHUB_OUTPUT
-      
-      
+
+          echo "cmd_id=$CMD_ID" >> "$GITHUB_OUTPUT"
+
       - name: Show Results
         run: |
           sleep 20
+
           aws ssm list-command-invocations \
-            --command-id "${{steps.health.outputs.cmd_id}}" --details \
-            --region us-east-1
-            --query "CommandInvocations[*].{Instance:InstanceId,Status,IP:CommandPlugins[0].Output}" \
+            --command-id "${{ steps.health.outputs.cmd_id }}" \
+            --details \
+            --region us-east-1 \
+            --query "CommandInvocations[*].{Instance:InstanceId,Status:Status,Output:CommandPlugins[0].Output}" \
             --output text
-          
+
           FAILED=$(aws ssm list-command-invocations \
-            --command-id "${{steps.health.outputs.cmd_id}}" --details \
+            --command-id "${{ steps.health.outputs.cmd_id }}" \
+            --details \
             --query "length(CommandInvocations[?Status=='Failed'])" \
             --output text \
-            --region us-east-1
-            )
+            --region us-east-1)
 
-          [ "$FAILED" -gt 0 ] && \
-          echo "::error::Health Check Failed on $FAILED instances" && \
-          exit 1
+          if [ "$FAILED" -gt 0 ]; then
+            echo "::error::Health Check Failed on $FAILED instances"
+            exit 1
+          fi
 
           echo "ALL Instances Healthy ✅"
